### ISSUE TITLE
Issues when compiling FMU from OpenModelica 

### ISSUE THREAD

**Issue by LBoese** [creative-connections/Bodylight-VirtualMachine#7]
Firstly: Great Work. Unfortunately I cannot get the FMU Compiler running on the Virtual Machine. The Vagrant installation was successful, but i get the following error code when I try to compile a fmu:

=== Processing file /home/vagrant/Bodylight.js-FMU-Compiler/input/CostFunction.fmu ===
Compiling OpenModelica FMU, log: /home/vagrant/Bodylight.js-FMU-Compiler/output/CostFunction.log
mkdir: cannot create directory ‘/work’: Permission denied
checkdir:  cannot create extraction directory: /work/build/fmu
           No such file or directory
warning: failed to load external entity "/work/build/fmu/modelDescription.xml"
cp: cannot stat ‘/work/build/fmu/modelDescription.xml’: No such file or directory
openmodelica.sh: line 28: cd: /work/build/fmu/sources: No such file or directory
configure: ./configure "CFLAGS=-Wno-unused-value -Wno-logical-op-parentheses" CPPFLAGS=-DOMC_MINIMAL_METADATA=1
emconfigure: error: './configure "CFLAGS=-Wno-unused-value -Wno-logical-op-parentheses" CPPFLAGS=-DOMC_MINIMAL_METADATA=1' failed: [Errno 2] No such file or directory: './configure'
make: make -Wno-unused-value
make: *** No targets specified and no makefile found.  Stop.
emmake: error: 'make -Wno-unused-value' failed (2)
openmodelica.sh: line 35: cd: /work/build/fmu: No such file or directory
emcc: error: '--post-js': file not found: '/work/sources/glue.js'
	zip warning: name not matched: /work/build/fmu/CostFunction.js
	zip warning: name not matched: /work/build/modelDescription.xml

zip error: Nothing to do! (/work/build/CostFunction.zip)
rm: cannot remove ‘/work/build/fmu/CostFunction.js’: No such file or directory
rm: cannot remove ‘/work/build/modelDescription.xml’: No such file or directory
ERROR: compilation unsuccessful, check log for details.

------------------------------------------------------------------

Could it be that the vagrant user needs higher user rights?

**Comment by TomasKulhanek** [comment]
Sorry, this is known issue. Compiling FMU from OpenModelica is not yet supported in this VM. For OM prior 1.16 we had some docker configuration which was able to compile the FMU co-simulation with Euler solver. OM since 1.16 introduces some export of FMU with CVODE solver, however, we had no resources (time) to update scripts and no one except you showed an insterest. 
The compiler/openmodelica.sh expects docker environment. To fix this issue 

1. the script compiler/openmodelica.sh needs to be updated similar way as the script in compiler/dymola.sh - the paths should point to /home/vagrant/Bodylight-Compiler ....
2. the script compiler/openmodelica.sh should be upgraded per instructions in OpenModelica 1.16+ documentation to download and include CVODE solver with source codes in FMU

Note that FMU's generated by Dymola tool with source codes are supported, so if you want to test the Bodylight.js technology, I recommend this way.

**Comment by TomasKulhanek** [comment]
I've fixed the script openmodelica.sh - commited in creative-connections/Bodylight.js-FMU-Compiler repository. To see it working in current VM - do start a terminal and 
``` 
cd /home/vagrant/Bodylight.js-FMU-Compiler
git pull
```
and try to compile FMU again using e.g. the web service.

**Comment by TomasKulhanek** [comment]
Reopening to verify whether fix works for @LBoese. Could you please check/verify that your CostFunction.fmu compiles as expected?

**Comment by LBoese** [comment]
Thank you for fixing. The Complation of the CostFunction.FMU I took from Bodylight-notebooks-master\GlobalOptimization works now. But i cant get my own FMUs working. 

I open the CostFunction.mo in Open Modelica 1.18 and export it as FMU. Then the Compiler will compile the FMU but only ModelDescription,xml will be in the Zip Folder but no *,js file? Do you have an idea where the problem results from?

I have attached the FMU I have created.

[CostFunctionFMU.zip](https://github.com/creative-connections/Bodylight-VirtualMachine/files/7497443/CostFunctionFMU.zip)

**Comment by TomasKulhanek** [comment]
Hi, the FMU was generated with CVODE solver. There are additional steps in OpenModelica 1.16 and 1.18 documentation to add the CVODE sources into FMU: "To have CVODE in a SourceCode FMU the user needs to add all sources for SUNDIALS manualy and create a build script as well."https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/fmitlm.html#fmi-export 

Our compiler build script do not automate the build process with sundials sources yet. So you can either

1. EITHER export fmu with explicit Euler as a solver }see screenshot how to set it in OMEdit)
2. OR download, install sundials CVODE manually, add includes and sources dir into `openmodelica.sh` script and try to compile FMU again.

I may try to dedicate some time to look and update the scripts officially later - if you will succeed earlier, let us know.

![VirtualBoxVM_s7BxdclxfD](https://user-images.githubusercontent.com/1429487/141463554-320a989d-7d1d-4d5a-8513-4300148c4023.png)

**Comment by TomasKulhanek** [comment]
closing this issue. Related issue to support FMU from OpenModelica with CVODE is reported at https://github.com/creative-connections/Bodylight.js-FMU-Compiler/issues/4
